### ISSUE TITLE
Typo in linearalgebra.pdf

### ISSUE THREAD

**Issue by elkalt** [louismeunier/notes#1]
- File name: linearalgebra.pdf
- Page/line numbers: page 18, section 2.4.3
- Description: all vectors are called v1, should be v1, v2, v3

**Comment by louismeunier** [comment]
Fixed by [#7ac9789c7113db2630840dd9eb42ac10833253e6](https://github.com/louismeunier/notes/commit/7ac9789c7113db2630840dd9eb42ac10833253e6)
